import Layout from "@/components/Layout";
import Career from "@/components/career/Career";
import Head from "next/head";
import React from "react";
import { getJob } from "../../../lib/getJob";

export default function Careers({ job }: any) {
  console.log(job);
  return (
    <Layout>
      <Head>
        <title>Careers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Career opening={job} />
    </Layout>
  );
}

export const getStaticProps = async () => {
  const job = await getJob();

  return {
    props: { job },
  };
};
