import Image from "next/image";
import { Inter } from "next/font/google";
import Link from "next/link";
import Layout from "@/components/Layout";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Seguray &mdash; Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center h-[100vh] justify-center flex-col">
        <h1>Welcome</h1>
        <Link href="/about" className="text-blue-800">
          Go to about page
        </Link>
      </main>
    </Layout>
  );
}
