import React from "react";
import { BsArrowUpRight } from "react-icons/bs";
import Hero from "@/components/products/Hero";
import Features from "@/components/products/Features";
import Benefits from "@/components/products/Benefits";
import Layout from "@/components/Layout";
import Head from "next/head";

const index = () => {
  return (
    <Layout>
      <Head>
        <title>Our Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Features />
      <Benefits />
    </Layout>
  );
};

export default index;
